globalvar ChaingunSnd;
globalvar DeathSnd1;
globalvar DeathSnd2;
globalvar ExplosionSnd;
globalvar FlamethrowerSnd;
globalvar IntelGetSnd;
globalvar IntelPutSnd;
globalvar JumpSnd;
globalvar MedigunSnd;
globalvar RespawnSnd;
globalvar RevolverSnd;
globalvar KnifeSnd;
globalvar RocketSnd;
globalvar ShotgunSnd;
globalvar VictorySnd;
globalvar FailureSnd;
globalvar SentryAlert;
globalvar SentryIdle;
globalvar SniperSnd;
globalvar MinegunSnd;
globalvar CbntHealSnd;
globalvar MedichaingunSnd;
globalvar IntelDropSnd;
globalvar Splat;
globalvar Gibbing;
globalvar CompressionBlastSnd;
globalvar BladeSnd;
globalvar NoticeSnd;
globalvar DeathCamSnd;
globalvar UberStartSnd;
globalvar UberEndSnd;
globalvar UberIdleSnd;
globalvar UberChargedSnd;
globalvar CPBeginCapSnd;
globalvar CPCapturedSnd;
globalvar CPDefendedSnd;
globalvar CountDown1Snd;
globalvar CountDown2Snd;
globalvar SirenSnd;
globalvar SentryFloorSnd;
globalvar SentryBuildSnd;
globalvar PickupSnd;

ChaingunSnd = faudio_new_generator(ChaingunSndS);
//show_debug_message("genid"+string(faudio_new_generator(ChaingunSndS)))
DeathSnd1 = faudio_new_generator(DeathSnd1S);
DeathSnd2 = faudio_new_generator(DeathSnd2S);
ExplosionSnd = faudio_new_generator(ExplosionSndS);
FlamethrowerSnd = faudio_new_generator(FlamethrowerSndS);
IntelGetSnd = faudio_new_generator(IntelGetSndS);
IntelPutSnd = faudio_new_generator(IntelPutSndS);
JumpSnd = faudio_new_generator(JumpSndS);
MedigunSnd = faudio_new_generator(MedigunSndS);
RespawnSnd = faudio_new_generator(RespawnSndS);
RevolverSnd = faudio_new_generator(RevolverSndS);
KnifeSnd = faudio_new_generator(KnifeSndS);
RocketSnd = faudio_new_generator(RocketSndS);
ShotgunSnd = faudio_new_generator(ShotgunSndS);
VictorySnd = faudio_new_generator(VictorySndS);
FailureSnd = faudio_new_generator(FailureSndS);
SentryAlert = faudio_new_generator(SentryAlertS);
SentryIdle = faudio_new_generator(SentryIdleS);
SniperSnd = faudio_new_generator(SniperSndS);
MinegunSnd = faudio_new_generator(MinegunSndS);
CbntHealSnd = faudio_new_generator(CbntHealSndS);
MedichaingunSnd = faudio_new_generator(MedichaingunSndS);
IntelDropSnd = faudio_new_generator(IntelDropSndS);
Splat = faudio_new_generator(SplatS);
Gibbing = faudio_new_generator(GibbingS);
CompressionBlastSnd = faudio_new_generator(CompressionBlastSndS);
BladeSnd = faudio_new_generator(BladeSndS);
NoticeSnd = faudio_new_generator(NoticeSndS);
DeathCamSnd = faudio_new_generator(DeathCamSndS);
UberStartSnd = faudio_new_generator(UberStartSndS);
UberEndSnd = faudio_new_generator(UberEndSndS);
UberIdleSnd = faudio_new_generator(UberIdleSndS);
UberChargedSnd = faudio_new_generator(UberChargedSndS);
CPBeginCapSnd = faudio_new_generator(CPBeginCapSndS);
CPCapturedSnd = faudio_new_generator(CPCapturedSndS);
CPDefendedSnd = faudio_new_generator(CPDefendedSndS);
CountDown1Snd = faudio_new_generator(CountDown1SndS);
CountDown2Snd = faudio_new_generator(CountDown2SndS);
SirenSnd = faudio_new_generator(SirenSndS);
SentryFloorSnd = faudio_new_generator(SentryFloorSndS);
SentryBuildSnd = faudio_new_generator(SentryBuildSndS);
PickupSnd = faudio_new_generator(PickupSndS);
