globalvar ChaingunSndS;
globalvar DeathSnd1S;
globalvar DeathSnd2S;
globalvar ExplosionSndS;
globalvar FlamethrowerSndS;
globalvar IntelGetSndS;
globalvar IntelPutSndS;
globalvar JumpSndS;
globalvar MedigunSndS;
globalvar RespawnSndS;
globalvar RevolverSndS;
globalvar KnifeSndS;
globalvar RocketSndS;
globalvar ShotgunSndS;
globalvar VictorySndS;
globalvar FailureSndS;
globalvar SentryAlertS;
globalvar SentryIdleS;
globalvar SniperSndS;
globalvar MinegunSndS;
globalvar CbntHealSndS;
globalvar MedichaingunSndS;
globalvar IntelDropSndS;
globalvar SplatS;
globalvar GibbingS;
globalvar CompressionBlastSndS;
globalvar BladeSndS;
globalvar NoticeSndS;
globalvar DeathCamSndS;
globalvar UberStartSndS;
globalvar UberEndSndS;
globalvar UberIdleSndS;
globalvar UberChargedSndS;
globalvar CPBeginCapSndS;
globalvar CPCapturedSndS;
globalvar CPDefendedSndS;
globalvar CountDown1SndS;
globalvar CountDown2SndS;
globalvar SirenSndS;
globalvar SentryFloorSndS;
globalvar SentryBuildSndS;
globalvar PickupSndS;

ChaingunSndS = faudio_new_sample("Sound/ChaingunSnd.wav");
//show_debug_message("sample"+string(file_exists(working_directory+"\Sound\ChaingunSnd.wav"))+working_directory+"\Sound\ChaingunSnd.wav")
//show_debug_message("sampleid"+string(faudio_new_sample(working_directory+"\Sound\ChaingunSnd.wav")))
DeathSnd1S = faudio_new_sample("Sound/DeathSnd1.wav");
DeathSnd2S = faudio_new_sample("Sound/DeathSnd2.wav");
ExplosionSndS = faudio_new_sample("Sound/ExplosionSnd.wav");
FlamethrowerSndS = faudio_new_sample("Sound/FlamethrowerSnd.wav");
IntelGetSndS = faudio_new_sample("Sound/IntelGetSnd.wav");
IntelPutSndS = faudio_new_sample("Sound/IntelPutSnd.wav");
JumpSndS = faudio_new_sample("Sound/JumpSnd.wav");
MedigunSndS = faudio_new_sample("Sound/MedigunSnd.wav");
RespawnSndS = faudio_new_sample("Sound/RespawnSnd.wav");
RevolverSndS = faudio_new_sample("Sound/RevolverSnd.wav");
KnifeSndS = faudio_new_sample("Sound/KnifeSnd.wav");
RocketSndS = faudio_new_sample("Sound/RocketSnd.wav");
ShotgunSndS = faudio_new_sample("Sound/ShotgunSnd.wav");
VictorySndS = faudio_new_sample("Sound/VictorySnd.wav");
FailureSndS = faudio_new_sample("Sound/FailureSnd.wav");
SentryAlertS = faudio_new_sample("Sound/SentryAlert.wav");
SentryIdleS = faudio_new_sample("Sound/SentryIdle.wav");
SniperSndS = faudio_new_sample("Sound/SniperSnd.wav");
MinegunSndS = faudio_new_sample("Sound/MinegunSnd.wav");
CbntHealSndS = faudio_new_sample("Sound/CbntHealSnd.wav");
MedichaingunSndS = faudio_new_sample("Sound/MedichaingunSnd.wav");
IntelDropSndS = faudio_new_sample("Sound/IntelDropSnd.wav");
SplatS = faudio_new_sample("Sound/Splat.wav");
GibbingS = faudio_new_sample("Sound/Gibbing.wav");
BladeSndS = faudio_new_sample("Sound/BladeSnd.wav");
NoticeSndS = faudio_new_sample("Sound/NoticeSnd.wav");
DeathCamSndS = faudio_new_sample("Sound/DeathCamSnd.wav");
UberStartSndS = faudio_new_sample("Sound/UberStartSnd.wav");
UberEndSndS = faudio_new_sample("Sound/UberEndSnd.wav");
UberIdleSndS = faudio_new_sample("Sound/UberIdleSnd.wav");
UberChargedSndS = faudio_new_sample("Sound/UberChargedSnd.wav");
CPBeginCapSndS = faudio_new_sample("Sound/CPBeginCapSnd.wav");
CPCapturedSndS = faudio_new_sample("Sound/CPCapturedSnd.wav");
CPDefendedSndS = faudio_new_sample("Sound/CPDefendedSnd.wav");
CountDown1SndS = faudio_new_sample("Sound/CountDown1Snd.wav");
CountDown2SndS = faudio_new_sample("Sound/CountDown2Snd.wav");
SirenSndS = faudio_new_sample("Sound/SirenSnd.wav");
SentryFloorSndS = faudio_new_sample("Sound/SentryFloorSnd.wav");
SentryBuildSndS = faudio_new_sample("Sound/SentryBuildSnd.wav");
PickupSndS = faudio_new_sample("Sound/PickupSnd.wav");
CompressionBlastSndS = faudio_new_sample("Sound/CompressionBlastSnd.wav");
