// Initialize all samples

globalvar BladeSndS;
globalvar BurningSndS;
globalvar CPBeginCapSndS;
globalvar CPCapturedSndS;
globalvar CPDefendedSndS;
globalvar CbntHealSndS;
globalvar ChaingunSndS;
globalvar CompressionBlastSndS;
globalvar CountDown1SndS;
globalvar CountDown2SndS;
globalvar DeathCamSndS;
globalvar DeathSnd1S;
globalvar DeathSnd2S;
globalvar DominationSndS;
globalvar ExplosionSndS;
globalvar FailureSndS;
globalvar FlamethrowerSndS;
globalvar GibbingS;
globalvar ImpactSndS;
globalvar IntelDropSndS;
globalvar IntelGetSndS;
globalvar IntelPutSndS;
globalvar JumpSndS;
globalvar KnifeSndS;
globalvar MedichaingunSndS;
globalvar MedigunSndS;
globalvar MinegunSndS;
globalvar MinigunShotImpactSndS;
globalvar NoticeSndS;
globalvar PickupSndS;
globalvar PowerShotSndS;
globalvar RespawnSndS;
globalvar RevengeSndS;
globalvar RevolverShotImpactSndS;
globalvar RevolverSndS;
globalvar RifleMetalSndS;
globalvar RifleShotImpactSndS;
globalvar RifleWorldSndS;
globalvar RocketFireSndS;
globalvar RocketTravelSndS;
globalvar SentryAlertS;
globalvar SentryBuildSndS;
globalvar SentryFloorSndS;
globalvar SentryIdleS;
globalvar ShotReflectSndS;
globalvar ShotTravelSndS;
globalvar ShotgunShotImpactSndS;
globalvar ShotgunSndS;
globalvar SirenSndS;
globalvar SniperSndS;
globalvar SplatS;
globalvar UberChargedSndS;
globalvar UberEndSndS;
globalvar UberIdleSndS;
globalvar UberStartSndS;
globalvar VictorySndS;

BladeSndS = create_sample("/Sound/BladeSnd.ogg");
BurningSndS = create_sample("/Sound/BurningSnd.ogg");
CPBeginCapSndS = create_sample("/Sound/CPBeginCapSnd.ogg");
CPCapturedSndS = create_sample("/Sound/CPCapturedSnd.ogg");
CPDefendedSndS = create_sample("/Sound/CPDefendedSnd.ogg");
CbntHealSndS = create_sample("/Sound/CbntHealSnd.ogg");
ChaingunSndS = create_sample("/Sound/ChaingunSnd.ogg");
CompressionBlastSndS = create_sample("/Sound/CompressionBlastSnd.ogg");
CountDown1SndS = create_sample("/Sound/CountDown1Snd.ogg");
CountDown2SndS = create_sample("/Sound/CountDown2Snd.ogg");
DeathCamSndS = create_sample("/Sound/DeathCamSnd.ogg");
DeathSnd1S = create_sample("/Sound/DeathSnd1.ogg");
DeathSnd2S = create_sample("/Sound/DeathSnd2.ogg");
DominationSndS = create_sample("/Sound/DominationSnd.ogg");
ExplosionSndS = create_sample("/Sound/ExplosionSnd.ogg");
FailureSndS = create_sample("/Sound/FailureSnd.ogg");
FlamethrowerSndS = create_sample("/Sound/FlamethrowerSnd.ogg");
GibbingS = create_sample("/Sound/Gibbing.ogg");
ImpactSndS = create_sample("/Sound/ImpactSnd.ogg");
IntelDropSndS = create_sample("/Sound/IntelDropSnd.ogg");
IntelGetSndS = create_sample("/Sound/IntelGetSnd.ogg");
IntelPutSndS = create_sample("/Sound/IntelPutSnd.ogg");
JumpSndS = create_sample("/Sound/JumpSnd.ogg");
KnifeSndS = create_sample("/Sound/KnifeSnd.ogg");
MedichaingunSndS = create_sample("/Sound/MedichaingunSnd.ogg");
MedigunSndS = create_sample("/Sound/MedigunSnd.ogg");
MinegunSndS = create_sample("/Sound/MinegunSnd.ogg");
MinigunShotImpactSndS = create_sample("/Sound/MinigunShotImpactSnd.ogg");
NoticeSndS = create_sample("/Sound/NoticeSnd.ogg");
PickupSndS = create_sample("/Sound/PickupSnd.ogg");
PowerShotSndS = create_sample("/Sound/PowerShotSnd.ogg");
RespawnSndS = create_sample("/Sound/RespawnSnd.ogg");
RevengeSndS = create_sample("/Sound/RevengeSnd.ogg");
RevolverShotImpactSndS = create_sample("/Sound/RevolverShotImpactSnd.ogg");
RevolverSndS = create_sample("/Sound/RevolverSnd.ogg");
RifleMetalSndS = create_sample("/Sound/RifleMetalSnd.ogg");
RifleShotImpactSndS = create_sample("/Sound/RifleShotImpactSnd.ogg");
RifleWorldSndS = create_sample("/Sound/RifleWorldSnd.ogg");
RocketFireSndS = create_sample("/Sound/RocketFireSnd.ogg");
RocketTravelSndS = create_sample("/Sound/RocketTravelSnd.ogg");
SentryAlertS = create_sample("/Sound/SentryAlert.ogg");
SentryBuildSndS = create_sample("/Sound/SentryBuildSnd.ogg");
SentryFloorSndS = create_sample("/Sound/SentryFloorSnd.ogg");
SentryIdleS = create_sample("/Sound/SentryIdle.ogg");
ShotReflectSndS = create_sample("/Sound/ShotReflectSnd.ogg");
ShotTravelSndS = create_sample("/Sound/ShotTravelSnd.ogg");
ShotgunShotImpactSndS = create_sample("/Sound/ShotgunShotImpactSnd.ogg");
ShotgunSndS = create_sample("/Sound/ShotgunSnd.ogg");
SirenSndS = create_sample("/Sound/SirenSnd.ogg");
SniperSndS = create_sample("/Sound/SniperSnd.ogg");
SplatS = create_sample("/Sound/Splat.ogg");
UberChargedSndS = create_sample("/Sound/UberChargedSnd.ogg");
UberEndSndS = create_sample("/Sound/UberEndSnd.ogg");
UberIdleSndS = create_sample("/Sound/UberIdleSnd.ogg");
UberStartSndS = create_sample("/Sound/UberStartSnd.ogg");
VictorySndS = create_sample("/Sound/VictorySnd.ogg");
