globalvar ChaingunSndS;
globalvar DeathSnd1S;
globalvar DeathSnd2S;
globalvar ExplosionSndS;
globalvar FlamethrowerSndS;
globalvar IntelGetSndS;
globalvar IntelPutSndS;
globalvar JumpSndS;
globalvar MedigunSndS;
globalvar RespawnSndS;
globalvar RevolverSndS;
globalvar KnifeSndS;
globalvar RocketSndS;
globalvar ShotgunSndS;
globalvar VictorySndS;
globalvar FailureSndS;
globalvar SentryAlertS;
globalvar SentryIdleS;
globalvar SniperSndS;
globalvar MinegunSndS;
globalvar CbntHealSndS;
globalvar MedichaingunSndS;
globalvar IntelDropSndS;
globalvar SplatS;
globalvar GibbingS;
globalvar CompressionBlastSndS;
globalvar BladeSndS;
globalvar NoticeSndS;
globalvar DeathCamSndS;
globalvar UberStartSndS;
globalvar UberEndSndS;
globalvar UberIdleSndS;
globalvar UberChargedSndS;
globalvar CPBeginCapSndS;
globalvar CPCapturedSndS;
globalvar CPDefendedSndS;
globalvar CountDown1SndS;
globalvar CountDown2SndS;
globalvar SirenSndS;
globalvar SentryFloorSndS;
globalvar SentryBuildSndS;
globalvar PickupSndS;

ChaingunSndS = faudio_new_sample("Sound/ChaingunSnd.ogg");
DeathSnd1S = faudio_new_sample("Sound/DeathSnd1.ogg");
DeathSnd2S = faudio_new_sample("Sound/DeathSnd2.ogg");
ExplosionSndS = faudio_new_sample("Sound/ExplosionSnd.ogg");
FlamethrowerSndS = faudio_new_sample("Sound/FlamethrowerSnd.ogg");
IntelGetSndS = faudio_new_sample("Sound/IntelGetSnd.ogg");
IntelPutSndS = faudio_new_sample("Sound/IntelPutSnd.ogg");
JumpSndS = faudio_new_sample("Sound/JumpSnd.ogg");
MedigunSndS = faudio_new_sample("Sound/MedigunSnd.ogg");
RespawnSndS = faudio_new_sample("Sound/RespawnSnd.ogg");
RevolverSndS = faudio_new_sample("Sound/RevolverSnd.ogg");
KnifeSndS = faudio_new_sample("Sound/KnifeSnd.ogg");
RocketSndS = faudio_new_sample("Sound/RocketSnd.ogg");
ShotgunSndS = faudio_new_sample("Sound/ShotgunSnd.ogg");
VictorySndS = faudio_new_sample("Sound/VictorySnd.ogg");
FailureSndS = faudio_new_sample("Sound/FailureSnd.ogg");
SentryAlertS = faudio_new_sample("Sound/SentryAlert.ogg");
SentryIdleS = faudio_new_sample("Sound/SentryIdle.ogg");
SniperSndS = faudio_new_sample("Sound/SniperSnd.ogg");
MinegunSndS = faudio_new_sample("Sound/MinegunSnd.ogg");
CbntHealSndS = faudio_new_sample("Sound/CbntHealSnd.ogg");
MedichaingunSndS = faudio_new_sample("Sound/MedichaingunSnd.ogg");
IntelDropSndS = faudio_new_sample("Sound/IntelDropSnd.ogg");
SplatS = faudio_new_sample("Sound/Splat.ogg");
GibbingS = faudio_new_sample("Sound/Gibbing.ogg");
BladeSndS = faudio_new_sample("Sound/BladeSnd.ogg");
NoticeSndS = faudio_new_sample("Sound/NoticeSnd.ogg");
DeathCamSndS = faudio_new_sample("Sound/DeathCamSnd.ogg");
UberStartSndS = faudio_new_sample("Sound/UberStartSnd.ogg");
UberEndSndS = faudio_new_sample("Sound/UberEndSnd.ogg");
UberIdleSndS = faudio_new_sample("Sound/UberIdleSnd.ogg");
UberChargedSndS = faudio_new_sample("Sound/UberChargedSnd.ogg");
CPBeginCapSndS = faudio_new_sample("Sound/CPBeginCapSnd.ogg");
CPCapturedSndS = faudio_new_sample("Sound/CPCapturedSnd.ogg");
CPDefendedSndS = faudio_new_sample("Sound/CPDefendedSnd.ogg");
CountDown1SndS = faudio_new_sample("Sound/CountDown1Snd.ogg");
CountDown2SndS = faudio_new_sample("Sound/CountDown2Snd.ogg");
SirenSndS = faudio_new_sample("Sound/SirenSnd.ogg");
SentryFloorSndS = faudio_new_sample("Sound/SentryFloorSnd.ogg");
SentryBuildSndS = faudio_new_sample("Sound/SentryBuildSnd.ogg");
PickupSndS = faudio_new_sample("Sound/PickupSnd.ogg");
CompressionBlastSndS = faudio_new_sample("Sound/CompressionBlastSnd.ogg");
