#!/usr/bin/env python3
"""Prepare a copy of the GG2 source tree for ENIGMA.

Stopgap for ENIGMA bugs, so the repo source stays the untouched GM8 game.
Every change happens on a copy, in this order:

1. patches/*.patch: hand-written changes (menu actions without
   execute_string, plugins disabled, ...), marked TODO(enigma) or
   PLUGINS(disabled) in the patched code.
2. rewrites: renames (char, fct_ bindings, headless helpers).
3. PATCHES: small edits that match rewritten text.

ENIGMA's own bugs are fixed in the jaasonw/enigma-dev fork (gg2-fixes).

Usage: prebuild.py <Source/gg2> <out dir> [--stub-extensions] [--headless]
                   [--faucet-src <Faucet checkout>]
"""

import argparse
import html
import re
import shutil
import subprocess
import sys
from pathlib import Path

# Faucet Networking API. Prefixed with fct_ because buffer_* etc. clash with
# ENIGMA built-ins (this matches Faucet's own fct_ variant).
FAUCET = """append_file_to_buffer bit_get bit_set buffer_bytes_left buffer_clear
buffer_create buffer_destroy buffer_set_readpos buffer_size build_ubyte
debug_handles ipv4_lookup_create ipv6_lookup_create ip_is_v4 ip_is_v6
ip_lookup_create ip_lookup_destroy ip_lookup_has_next ip_lookup_next_result
ip_lookup_ready mac_addrs read_base64 read_byte read_double read_float read_hex
read_int read_short read_string read_ubyte read_uint read_ushort
set_little_endian set_little_endian_global socket_accept socket_connecting
socket_destroy socket_destroy_abortive socket_error socket_handle_io
socket_has_error socket_local_port socket_receivebuffer_size socket_remote_ip
socket_remote_port socket_send socket_sendbuffer_limit socket_sendbuffer_size
tcp_connect tcp_eof tcp_listen tcp_listening_v4 tcp_listening_v6 tcp_receive
tcp_receive_available tcp_set_nodelay udp_bind udp_broadcast udp_receive
udp_send write_base64 write_buffer write_buffer_part write_buffer_to_file
write_byte write_double write_float write_hex write_int write_short
write_string write_ubyte write_uint write_ushort read_binary_string
read_cstring read_delimited_binary_string read_delimited_string
write_binary_string""".split()

# Other extension functions with no native build yet (Faucet Forwarding).
OTHER_EXTENSIONS = """upnp_set_description upnp_discover upnp_error_string
upnp_forward_port upnp_release_port""".split()

# GG2DLL: GM8 gets these from the .gex; ENIGMA builds load libgg2dll.so (built
# by build.sh next to the game) with external_define on first use.
GG2DLL_FUNCS = {  # GML name: (C symbol, return type, argument types)
    "GG2DLL_compute_MD5": ("compute_MD5", "ty_string", ["ty_string"]),
    "GG2DLL_embed_PNG_leveldata": (
        "embed_PNG_leveldata",
        "ty_real",
        ["ty_string", "ty_string"],
    ),
    "GG2DLL_extract_PNG_leveldata": (
        "extract_PNG_leveldata",
        "ty_string",
        ["ty_string", "ty_string"],
    ),
    "GG2DLL_log_message": ("log_message", "ty_real", ["ty_string"]),
}


FAUCET_EXPORT_RE = re.compile(
    r'(?:DLLEXPORT|extern "C" __attribute__\(\(visibility\("default"\)\)\))\s+'
    r"(double|const char\s*\*|char\s*\*)\s*(\w+)\s*\(([^)]*)\)"
)


def faucet_scripts(faucet_src):
    """fct_* bindings to libfaucetnet.so (built by build.sh), from the exported
    C signatures in Faucet's source. Faucet functions that were GML scripts in
    the .gex (not used by GG2) raise an error instead."""
    exports = {}
    for f in sorted(Path(faucet_src, "faucet").rglob("*.cpp")):
        for m in FAUCET_EXPORT_RE.finditer(f.read_text(encoding="utf-8")):
            args = [a.strip() for a in m.group(3).split(",") if a.strip()]
            exports[m.group(2)] = (
                "ty_string" if "char" in m.group(1) else "ty_real",
                ["ty_string" if "char" in a else "ty_real" for a in args],
            )
    init = ["var dll;", 'dll = program_directory + "/libfaucetnet.so";']
    scripts = {}
    for name in FAUCET:
        gml = "fct_" + name
        if name not in exports:
            scripts[gml] = (
                f'show_error("{gml} is not available in ENIGMA builds", true);\n'
            )
            continue
        ret, args = exports[name]
        handle = f"global.{gml}_fn"
        types = "".join(f", {t}" for t in args)
        init.append(
            f'{handle} = external_define(dll, "{name}", dll_cdecl, {ret}, '
            f"{len(args)}{types});"
        )
        call_args = "".join(f", argument{i}" for i in range(len(args)))
        scripts[gml] = (
            "// ENIGMA-only binding, generated by prebuild.py\n"
            "if (!global.faucet_ready) faucet_init();\n"
            f"return external_call({handle}{call_args});\n"
        )
    init += [
        'external_call(external_define(dll, "dllStartup", dll_cdecl, ty_real, 0));',
        "global.faucet_ready = true;",
    ]
    scripts["faucet_init"] = "\n".join(init) + "\n"
    return scripts


def gg2dll_scripts():
    init = ["var dll;", 'dll = program_directory + "/libgg2dll.so";']
    scripts = {}
    for gml, (sym, ret, args) in GG2DLL_FUNCS.items():
        handle = f"global.{gml.lower()}_fn"
        init.append(
            f'{handle} = external_define(dll, "{sym}", dll_cdecl, {ret}, '
            f"{len(args)}, {', '.join(args)});"
        )
        call_args = "".join(f", argument{i}" for i in range(len(args)))
        scripts[gml] = (
            "// ENIGMA-only binding, generated by prebuild.py\n"
            "if (!global.gg2dll_ready) gg2dll_init();\n"
            f"return external_call({handle}{call_args});\n"
        )
    init.append("global.gg2dll_ready = true;")
    scripts["gg2dll_init"] = "\n".join(init) + "\n"
    return scripts


# char is a C++ type in EDL, so it can't be a GML variable name.
RENAMES = {"char": "char_"}

# GG2 scripts ENIGMA provides natively (GG2's versions use execute_string).
DROP_SCRIPTS = ["asset_get_index"]

# GM8 functions ENIGMA doesn't have, added as scripts of the same name.
COMPAT = {
    # Message box styling: cosmetic, ENIGMA uses native dialogs.
    **dict.fromkeys(
        [
            "message_background",
            "message_button",
            "message_text_font",
            "message_button_font",
            "message_input_font",
        ],
        "// no-op: ENIGMA uses native dialogs\n",
    ),
    # GM8 splash windows: open the page in the browser instead.
    "action_splash_web": "url_open(argument0);\n",
    "splash_show_web": "url_open(argument0);\n",
    "splash_set_main": "// no-op: no splash window\n",
    "splash_set_interrupt": "// no-op: no splash window\n",
    # Included files are shipped next to the binary instead of embedded.
    "export_include_file_location": "return file_copy(program_directory + "
    '"/" + argument0, argument1);\n',
}

# Extension stubs that need a non-zero result to fail cleanly.
STUB_OVERRIDES = {
    "upnp_error_string": 'return "UPnP port forwarding is not supported in this'
    ' build.";\n',
}

# Headless builds: no file dialogs, ask on the console.
HEADLESS_HELPERS = {
    "get_open_filename": (
        "gml_get_open_filename",
        'return get_string("File to open:", "");\n',
    ),
    "get_save_filename": (
        "gml_get_save_filename",
        'return get_string("File to save:", argument1);\n',
    ),
}

# Platform differences for ENIGMA (Linux) builds, applied to the build copy:
# (file, old text, new text). Each must match exactly once.
PATCH_DIR = Path(__file__).resolve().parent / "patches"

# Edits applied after the rewrites, so they match rewritten names (fct_).
PATCHES = [
    (
        "Scripts/Client/ClientBeginStep.gml",
        "switch(fct_read_ubyte(global.serverSocket)) {",
        'packetType = fct_read_ubyte(global.serverSocket); '
        'GG2DLL_log_message("Received server packet " + '
        'string(packetType)); switch(packetType) {',
    ),
    (
        "Scripts/Serialization/deserializeState.gml",
        "    with(MovingPlatform)\n        event_user(11);\n}",
        "    with(MovingPlatform)\n        event_user(11);\n}\n"
        'if(argument0 == 8) GG2DLL_log_message("FULL after players");',
    ),
    (
        "Scripts/Serialization/deserializeState.gml",
        "    deserialize(IntelligenceBlue);",
        "    deserialize(IntelligenceBlue);\n"
        '    GG2DLL_log_message("FULL after intel");',
    ),
    (
        "Scripts/Serialization/deserializeState.gml",
        "    with (HUD)\n        event_user(13);\n    \n    // read in",
        "    with (HUD)\n        event_user(13);\n"
        '    GG2DLL_log_message("FULL after HUD");\n'
        "    \n    // read in",
    ),
    (
        "Scripts/Serialization/deserializeState.gml",
        "        global.classlimits[a] = fct_read_ubyte(global.tempBuffer);",
        "        global.classlimits[a] = fct_read_ubyte(global.tempBuffer);\n"
        '    GG2DLL_log_message("FULL complete");',
    ),
    (
        "Scripts/Client/ClientBeginStep.gml",
        'promptRestartOrQuit("The Server sent unexpected data.");',
        'GG2DLL_log_message("Unexpected server packet " + '
        'string(packetType)); '
        'promptRestartOrQuit("The Server sent unexpected data (packet " + '
        'string(packetType) + ").");',
    ),
    # The updater downloads the Windows release zip and unpacks it with 7za.exe;
    # send Linux players to the releases page instead.
    (
        "Objects/Menus/Main Menu Elements/DevMessagePopup.events/"
        "Mouse global left pressed.xml",
        "room_goto(UpdaterRoom);",
        'url_open("https://github.com/Gang-Garrison-2/Gang-Garrison-2/releases");',
    ),
]

# GM8 strings have no escapes and may span lines.
SKIP_RE = re.compile(r'//[^\n]*|/\*.*?\*/|"[^"]*"|\'[^\']*\'', re.S)
CODE_TAG_RE = re.compile(
    r'(<argument kind="STRING">)(.*?)(</argument>)'
    r"|(<creationCode>)(.*?)(</creationCode>)",
    re.S,
)


def word_re(words):
    return re.compile(
        r"\b(" + "|".join(sorted(map(re.escape, words), key=len, reverse=True)) + r")\b"
    )


class Rewriter:
    def __init__(self, renames):
        self.rename_re = word_re(renames)
        self.renames = renames

    def code(self, text):
        out, last = [], 0
        for m in SKIP_RE.finditer(text):
            out += [self.rename_re.sub(lambda r: self.renames[r.group(1)], text[last : m.start()]), m.group(0)]
            last = m.end()
        out.append(self.rename_re.sub(lambda r: self.renames[r.group(1)], text[last:]))
        return "".join(out)


def apply_source_patches(out):
    # The repo source stays identical to the GM8 game; every hand-written
    # ENIGMA fix lives in patches/, applied in order to the build copy.
    for patch in sorted(PATCH_DIR.glob("*.patch")):
        with patch.open("rb") as f:
            result = subprocess.run(
                ["patch", "-s", "-p3", "--binary", "--forward",
                 "--no-backup-if-mismatch", "-r", "-", "-d", str(out)],
                stdin=f,
            )
        if result.returncode:
            sys.exit(f"prebuild: {patch.name} does not apply; refresh it against Source/gg2")


def apply_patches(out, patches):
    for rel, old, new in patches:
        path = out / rel
        text = path.read_text(encoding="utf-8")
        if text.count(old) != 1:
            sys.exit(f"prebuild: patch for {rel} matched {text.count(old)} times")
        path.write_text(text.replace(old, new), encoding="utf-8")


def drop_scripts(out, names):
    for name in names:
        (path,) = (out / "Scripts").rglob(f"{name}.gml")
        path.unlink()
        listing = path.parent / "_resources.list.xml"
        text = listing.read_text(encoding="utf-8")
        listing.write_text(
            text.replace(f'  <resource name="{name}" type="RESOURCE"/>\n', ""), encoding="utf-8"
        )


def add_script_group(out, group_name, scripts):
    group = out / "Scripts" / group_name
    group.mkdir()
    for name, code in scripts.items():
        (group / f"{name}.gml").write_text(code)
    (group / "_resources.list.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<resources>\n'
        + "".join(f'  <resource name="{n}" type="RESOURCE"/>\n' for n in scripts)
        + "</resources>\n"
    )
    top = out / "Scripts" / "_resources.list.xml"
    text = top.read_text(encoding="utf-8")
    top.write_text(
        text.replace(
            "<resources>\n",
            f'<resources>\n  <resource name="{group_name}" type="GROUP"/>\n',
            1,
        ),
        encoding="utf-8",
    )


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("src", type=Path)
    ap.add_argument("out", type=Path)
    ap.add_argument(
        "--stub-extensions",
        action="store_true",
        help="add return-0 scripts for native extensions",
    )
    ap.add_argument("--headless", action="store_true", help="build for widgets None")
    ap.add_argument(
        "--faucet-src",
        type=Path,
        help="Faucet-Networking-Extension checkout; bind libfaucetnet.so",
    )
    args = ap.parse_args()
    helpers = HEADLESS_HELPERS if args.headless else {}

    if args.out.exists():
        shutil.rmtree(args.out)
    shutil.copytree(args.src, args.out)
    apply_source_patches(args.out)

    renames = dict(RENAMES)
    renames.update({name: helper for name, (helper, _) in helpers.items()})
    renames.update({f: "fct_" + f for f in FAUCET})
    rw = Rewriter(renames)

    for f in sorted(args.out.rglob("*.gml")):
        f.write_text(rw.code(f.read_text(encoding="utf-8")), encoding="utf-8")

    def fix_tag(m):
        open_tag, body, close_tag = m.group(1, 2, 3) if m.group(1) else m.group(4, 5, 6)
        return open_tag + html.escape(rw.code(html.unescape(body)), quote=False) + close_tag

    for f in sorted(args.out.rglob("*.xml")):
        if f.name == "Constants.xml":
            continue
        original = f.read_text(encoding="utf-8")
        new = CODE_TAG_RE.sub(fix_tag, original)
        if new != original:
            f.write_text(new, encoding="utf-8")

    apply_patches(args.out, PATCHES)
    drop_scripts(args.out, DROP_SCRIPTS)
    add_script_group(args.out, "EnigmaHelpers", dict(helpers.values()) | COMPAT)
    bindings = gg2dll_scripts()
    if args.faucet_src:
        bindings |= faucet_scripts(args.faucet_src)
    add_script_group(args.out, "NativeBindings", bindings)
    if args.stub_extensions:
        stub = "// stub: native extension not built yet\nreturn 0;\n"
        names = [n for n in ["fct_" + f for f in FAUCET] if n not in bindings]
        names += OTHER_EXTENSIONS
        stubs = dict.fromkeys(names, stub) | STUB_OVERRIDES
        add_script_group(args.out, "ExtensionStubs", stubs)


if __name__ == "__main__":
    main()
